### ISSUE TITLE
RuntimeError: Stop_waiting response is expected

### ISSUE THREAD

**Issue by xiatingyu** [zhanglu-cst/ClassKG#2]
Hello 
When I run the pipeline.py, I got this error :

Traceback (most recent call last):
  File "pipeline.py", line 99, in <module>
    spawn(main, args = (), nprocs = world_size, join = True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/ClassKG-main/task/pipeline.py", line 41, in main
    set_multi_GPUs_envs(rank, world_size)
  File "/root/autodl-tmp/ClassKG-main/task/../compent/set_multi_GPUs.py", line 11, in set_multi_GPUs_envs
    dist.init_process_group('nccl', rank = rank, world_size = world_size)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Stop_waiting response is expected

Maybe it caused by the cuda version or pytorch version. So could you please share your pytorch version? Do you have any other solutions for this bug?

**Comment by zhanglu-cst** [comment]
This appears to be an error in initializing DDP.   
You can check as follows：
1、Make sure the variable GPUs in pipeline.py  is set correctly .  If you only have two GPUs, set  GPUs to "0,1"
2、Try running a simple program like image classification with DDP to verify that DDP is available on the machine.
