### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by xiatingyu** [zhanglu-cst/ClassKG#3]
Hello，I have run this code on dataset 20NF and my own dataset yahoo, they are both long datasets. And they both had the same problem. (I have run this code on AGNEWS and it's ok) 

Eval Model On Eval Set:
2022-05-07 05:37:49,796 yahoo INFO: rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
INFO:yahoo:rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
2022-05-07 05:37:49,875 yahoo INFO: rank:0, Load model success, other info:{}
INFO:yahoo:rank:0, Load model success, other info:{}
2022-05-07 05:37:49,883 yahoo INFO: rank:0, start eval
INFO:yahoo:rank:0, start eval
Traceback (most recent call last):
  File "yahoo.py", line 99, in <module>
    spawn(main, args = (), nprocs = world_size, join = True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/ClassKG-main/task/yahoo.py", line 81, in main
    sentences, labels = classifier_trainer.train_model(sentences = res_dict['sentences'],
  File "/root/autodl-tmp/ClassKG-main/task/../Models/Longformer_Classify/trainer_longformer_ST.py", line 53, in train_model
    sentences, labels, global_best = self.__do_train__(dataloader = dataloader_train, ITR = ITR,
  File "/root/autodl-tmp/ClassKG-main/task/../Models/Longformer_Classify/trainer_longformer_ST.py", line 189, in __do_train__
    self.checkpointer.load_from_filename(model = self.model,
  File "/root/autodl-tmp/ClassKG-main/task/../compent/checkpoint.py", line 92, in load_from_filename
    self.__load_from_file__(model, path, strict = strict)
  File "/root/autodl-tmp/ClassKG-main/task/../compent/checkpoint.py", line 95, in __load_from_file__
    data = torch.load(path, map_location = 'cpu')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by zhanglu-cst** [comment]
Hi, this looks like an error when reading an empty file. You can check to see if the corresponding saved file is empty. 
It's also unclear to me why there are empty files. Can you provide the log of the training to me?

**Comment by xiatingyu** [comment]
Here is the training output:
Eval Model On Eval Set:
2022-05-07 05:37:49,796 yahoo INFO: rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
INFO:yahoo:rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
2022-05-07 05:37:49,875 yahoo INFO: rank:0, Load model success, other info:{}
INFO:yahoo:rank:0, Load model success, other info:{}
2022-05-07 05:37:49,883 yahoo INFO: rank:0, start eval
INFO:yahoo:rank:0, start eval
Traceback (most recent call last):
  File "yahoo.py", line 99, in <module>
    spawn(main, args = (), nprocs = world_size, join = True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/ClassKG-main/task/yahoo.py", line 81, in main
    sentences, labels = classifier_trainer.train_model(sentences = res_dict['sentences'],
  File "/root/autodl-tmp/ClassKG-main/task/../Models/Longformer_Classify/trainer_longformer_ST.py", line 53, in train_model
    sentences, labels, global_best = self.__do_train__(dataloader = dataloader_train, ITR = ITR,
  File "/root/autodl-tmp/ClassKG-main/task/../Models/Longformer_Classify/trainer_longformer_ST.py", line 189, in __do_train__
    self.checkpointer.load_from_filename(model = self.model,
  File "/root/autodl-tmp/ClassKG-main/task/../compent/checkpoint.py", line 92, in load_from_filename
    self.__load_from_file__(model, path, strict = strict)
  File "/root/autodl-tmp/ClassKG-main/task/../compent/checkpoint.py", line 95, in __load_from_file__
    data = torch.load(path, map_location = 'cpu')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Here is the .log file:
2022-05-07 05:37:48,852 yahoo INFO: rank:0, save to file path:yahoo/itr_0_ST_3
2022-05-07 05:37:49,796 yahoo INFO: rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
2022-05-07 05:37:49,875 yahoo INFO: rank:0, Load model success, other info:{}
2022-05-07 05:37:49,883 yahoo INFO: rank:0, start eval
the code stop here.

**Comment by zhanglu-cst** [comment]
Hi, you can try to check the size of this file：yahoo/itr_0_ST_3.

**Comment by xiatingyu** [comment]
The size of yahoo/itr_0_ST_3 is same with yahoo/itr_0_ST_0/1/2

**Comment by xiatingyu** [comment]
I think maybe I found the reason for the error.
The code should run like this:
2022-05-07 02:54:49,586 yahoo INFO: rank:0, Loading model from:yahoo/itr_0_ST_2, model save time:Sat May  7 01:55:21 2022
2022-05-07 02:54:49,615 yahoo INFO: rank:1, Loading model from:yahoo/itr_0_ST_2, model save time:Sat May  7 01:55:21 2022
2022-05-07 02:54:49,672 yahoo INFO: rank:0, Load model success, other info:{}
2022-05-07 02:54:49,689 yahoo INFO: rank:0, start eval
2022-05-07 02:54:49,700 yahoo INFO: rank:1, Load model success, other info:{}
2022-05-07 02:54:49,711 yahoo INFO: rank:1, start eval

But, when it reports an error，it runs like this：
2022-05-07 05:37:48,852 yahoo INFO: rank:0, save to file path:yahoo/itr_0_ST_3
2022-05-07 05:37:49,796 yahoo INFO: rank:0, Loading model from:yahoo/itr_0_ST_3, model save time:Sat May  7 05:37:48 2022
2022-05-07 05:37:49,875 yahoo INFO: rank:0, Load model success, other info:{}
2022-05-07 05:37:49,883 yahoo INFO: rank:0, start eval

It seems like there is a problem with rank 1.

**Comment by xiatingyu** [comment]
It may also be a torch version problem, which version did you use? My torch is 1.9.0

**Comment by zhanglu-cst** [comment]
You can try a lower version of torch, such as 1.7.1. 
Moreover, try to use torch to load that checkpoint directly to see if there is an error.

**Comment by xiatingyu** [comment]
I have loaded that checkpoint directly using torch and there are no errors.
And I will try a lower version torch, hope it helpful.

**Comment by zhanglu-cst** [comment]
It is indeed a very strange problem, and I also suspect that it is caused by the version of torch.

**Comment by xiatingyu** [comment]
DGL need torch>=1.8.0, what a sad story.......

**Comment by xiatingyu** [comment]
I have modified the __load_from_file__ function in compent/checkpoint.py and added try before load model. Solved this problem.
    def __load_from_file__(self, model, path, strict):
        try:
            data = torch.load(path, map_location = 'cpu')
            model_time = data.pop('time')
            self.logger.info('Loading model from:{}, model save time:{}'.format(path, model_time))
            model_para = data.pop('model')
            keep_para = model_para
            if (hasattr(model, 'module')):
                model.module.load_state_dict(keep_para, strict=strict)
            else:
                model.load_state_dict(keep_para, strict=strict)
            self.logger.info('Load model success, other info:{}'.format(data))
        except:
            print('Load model error...')

It is very interesting that this problem only occurs in the case of long sentences.

**Comment by xiatingyu** [comment]
It is indeed possible, the version of transformers I am using now is 4.18.0
